version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-cleanarch.dev
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - bubble
  db:
    container_name: db.go-cleanarch
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --init-file /db/migrations/init.sql
    volumes:
      - ./db/migrations/init.sql:/db/migrations/init.sql
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cleanarch_go_db
    networks:
      - bubble
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper.dev
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bubble
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka.dev
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bubble

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop.dev
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    networks:
      - bubble

networks:
  bubble:
    external: true